#!/usr/bin/env python3
"""SI figure: a worked lipidomics acquisition queue generated by qg.

Builds a representative Lipidomics queue with the *real* qg engine
(``QueueGenerator``) using the shipped ``Lipidomics.standard`` QC pattern, on an
EXPLORIS instrument with the Vanquish well-plate sampler, dual-polarity
acquisition, and ``blocked_uniform`` run-order randomization. The point of the
figure is to *show* the lipidomics workflow the manuscript otherwise only names:

* a leading system-suitability block -- solvent blanks, the **EquiSPLASH**
  class-spanning internal-standard mix, a pooled-QC, and a six-point pooled-QC
  **dilution series** (``pooledQCDil1``--``pooledQCDil6``);
* the user samples, group-interleaved by ``blocked_uniform``;
* pooled-QC + internal-standard injections recurring through the run;
* **every** injection -- QC and sample alike -- acquired in **both** ionization
  polarities (the lower track shows the regular pos/neg pattern).

The sequence, polarities, and QC placement are taken verbatim from the generated
queue; nothing here is hand-drawn. (The ``Lipidomics.standard`` pattern does not
inject a NIST reference material, so none is shown.)

Run (qg must be importable -- use the qg/ environment):

    cd qg && uv run --with matplotlib python \\
        ../qg_article/pipeline/scripts/make_lipidomics_queue_figure.py

Output: figures/fig_lipidomics_queue.png
"""

from __future__ import annotations

import logging
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import Patch, Rectangle

logging.disable(logging.CRITICAL)  # silence qg's loguru/INFO chatter

from qg.apps.integrations.example_params import read_example_params  # noqa: E402
from qg.config_models.loader import qg_configuration  # noqa: E402
from qg.generator import QueueGenerator  # noqa: E402

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "fig_lipidomics_queue.png"

CLASS_COLORS = {
    "Blank": "#BFBFBF",
    "EquiSPLASH (IS)": "#8E44AD",
    "Pooled QC": "#2E86C1",
    "QC dilution series": "#16A085",
    "Control": "#4C78A8",
    "Treated": "#E45756",
    "KO": "#F2A900",
}
POL_COLORS = {"pos": "#CBD9EF", "neg": "#2F4B7C"}

plt.rcParams.update(
    {"font.family": "sans-serif", "font.sans-serif": ["Helvetica", "Arial", "DejaVu Sans"], "font.size": 8}
)


def _classify(name: str, slot_kind: str, grouping_var: str | None) -> str:
    if slot_kind == "user":
        return grouping_var or "sample"
    if name == "blank":
        return "Blank"
    if name == "EquiSPLASH":
        return "EquiSPLASH (IS)"
    if name == "pooledQC":
        return "Pooled QC"
    if name.startswith("pooledQCDil"):
        return "QC dilution series"
    return name


def main() -> int:
    config = qg_configuration()
    # Reproduce the exact queue shipped as a bundled example, so the figure and the
    # `qg lipidomics_standard.json` one-command example can never drift apart.
    _entry, queue_input = read_example_params("lipidomics_standard")
    rows = QueueGenerator(config, queue_input).build_rows().to_table()
    recs = rows.to_dicts()
    n = len(recs)
    classes = [_classify(r["sample_name"], r["slot_kind"], r.get("grouping_var")) for r in recs]
    pols = [r["polarity"] for r in recs]

    fig, ax = plt.subplots(figsize=(9.4, 3.3), dpi=300)
    for x, (cls, pol) in enumerate(zip(classes, pols, strict=True)):
        ax.add_patch(Rectangle((x, 1.15), 1, 0.85, facecolor=CLASS_COLORS.get(cls, "#333333"), edgecolor="white", linewidth=0.25))
        ax.add_patch(Rectangle((x, 0.10), 1, 0.55, facecolor=POL_COLORS[pol], edgecolor="white", linewidth=0.25))

    ax.set_xlim(0, n)
    ax.set_ylim(0, 2.55)
    ax.set_yticks([1.575, 0.375])
    ax.set_yticklabels(["injection\nclass", "polarity"])
    ax.set_xlabel(f"acquisition order (injection 1 to {n})")
    ax.set_xticks([0, 10, 20, 30, 40, 50, n])
    for spine in ("top", "right", "left"):
        ax.spines[spine].set_visible(False)
    ax.tick_params(axis="y", length=0)

    # Region brackets: leading system-suitability block vs the sample run.
    first_user = next(i for i, r in enumerate(recs) if r["slot_kind"] == "user")

    def bracket(x0: int, x1: int, label: str) -> None:
        ax.plot([x0 + 0.1, x1 - 0.1], [2.18, 2.18], color="#444444", linewidth=0.8)
        ax.text((x0 + x1) / 2, 2.26, label, ha="center", va="bottom", fontsize=7.2, color="#333333")

    bracket(0, first_user, "system-suitability block:\nblanks · EquiSPLASH IS · pooled QC · 6-pt dilution series")
    bracket(first_user, n, "user samples — group-interleaved (blocked_uniform), each in + and − polarity")

    class_order = ["Blank", "EquiSPLASH (IS)", "Pooled QC", "QC dilution series", "Control", "Treated", "KO"]
    fig.legend(
        handles=[Patch(facecolor=CLASS_COLORS[c], edgecolor="white", label=c) for c in class_order],
        loc="lower center", bbox_to_anchor=(0.5, 0.10), ncol=7, frameon=False, fontsize=7,
        title="injection class", handlelength=1.1, columnspacing=1.1, handletextpad=0.4,
    )
    fig.legend(
        handles=[Patch(facecolor=POL_COLORS[p], edgecolor="white", label=lab)
                 for p, lab in (("pos", "positive"), ("neg", "negative"))],
        loc="lower center", bbox_to_anchor=(0.5, 0.0), ncol=2, frameon=False, fontsize=7, title="polarity",
    )
    fig.suptitle("A worked lipidomics acquisition queue (Lipidomics.standard pattern, dual polarity)",
                 fontsize=10, fontweight="bold", y=0.99)
    fig.subplots_adjust(left=0.075, right=0.99, top=0.84, bottom=0.32)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(OUT, dpi=600, bbox_inches="tight")
    plt.close(fig)

    n_user = sum(1 for r in recs if r["slot_kind"] == "user")
    n_qc = n - n_user
    print(f"Wrote {OUT}")
    print(f"  {n} injections | {n_user} user (12 samples x2 polarities) | {n_qc} QC/standard | first user at index {first_user}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
