name: qg-test
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # TODO real deploy should change this!
      - SECRET_KEY=tueS8enudrae81-mnnoardunou9e8uelnudronudobpQA
    expose:
      - "8000"
    entrypoint:
      [
        "/app/.venv/bin/uvicorn",
        "qg.apps.bfabric_app:app",
        "--port",
        "8000",
        "--host",
        "0.0.0.0",
      ]
    volumes:
      - ./bfabric_cache:/app/bfabric_cache:ro
  caddy:
    image: caddy:2-alpine
    ports:
      - "9505:443"
    configs:
      - source: caddyfile
        target: /etc/caddy/Caddyfile
    volumes:
      - caddy_data:/data
    depends_on:
      - app
    restart: unless-stopped

configs:
  caddyfile:
    content: |
      localhost fgcz-r-039 fgcz-r-039.uzh.ch {
        tls internal
        reverse_proxy app:8000
      }

volumes:
  caddy_data:
