name: qg-queue
services:
  queue-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: qg-queue-app:latest
    environment:
      - SECRET_KEY=tueS8enudrae81-mnnoardunou9e8uelnudronudobpQA
    expose:
      - "8000"
    entrypoint:
      ["/app/.venv/bin/uvicorn", "qg.apps.bfabric_app_qg:app",
       "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ~/qg_configs_production/qg_configs:/app/qg_configs:rw
      - logs:/root/.qg/logs:rw

  caddy:
    image: caddy:2-alpine
    ports:
      - "9506:443"
    configs:
      - source: caddyfile
        target: /etc/caddy/Caddyfile
    volumes:
      - caddy_data:/data
    depends_on:
      - queue-app
    restart: unless-stopped

configs:
  caddyfile:
    content: |
      localhost fgcz-r-039 fgcz-r-039.uzh.ch {
        tls internal
        reverse_proxy queue-app:8000
      }

volumes:
  caddy_data:
  logs:
