"""Tests for PositionAssigner with different samplers and technologies."""

import pytest

from qg.config_models_samplers import (
    EvosepContainer,
    EvosepSampler,
    GridContainer,
    GridSampler,
)
from qg.params_models import InputSample
from qg.positions import (
    EvosepPositionGenerator,
    MClass48PositionGenerator,
    VanquishPositionGenerator,
)
from qg.strategies import (
    GeneratedPositionAssigner,
    InputPositionAssigner,
    create_position_assigner,
)


class TestGeneratedPositionAssigner:
    """Tests for GeneratedPositionAssigner (vial mode)."""

    def test_vanquish_vial_proteomics(self):
        """Vanquish vial mode with proteomics QC layout."""
        # Typed Vanquish config
        config = GridSampler(
            description="Vanquish test",
            plates=["Y", "R", "B", "G"],
            qc_plate="B",
            vial=GridContainer(
                container_type="Vial",
                position_source="generated",
                fill_order="row_major",
                position_format="{plate}:{row}{col}",
                sample_rows=["A", "B", "C", "D", "E"],
                cols=[1, 2, 3, 4, 5, 6, 7, 8, 9],
            ),
        )
        generator = VanquishPositionGenerator(config, "vial")

        # Proteomics QC layout (from qc_layouts.toml)
        qc_layout = {
            "QC01": "B:F9",
            "QC03dia": "B:F8",
            "clean": "B:F7",
        }

        assigner = GeneratedPositionAssigner(sampler=generator, qc_layout=qc_layout)

        # Queue structure: start QCs, 3 user samples, end QCs
        structure = ["QC03dia", "QC01", "default", "default", "default", "clean", "QC01"]
        samples = [
            InputSample(sample_name="s1", sample_id=1),
            InputSample(sample_name="s2", sample_id=2),
            InputSample(sample_name="s3", sample_id=3),
        ]

        positions = assigner(structure, samples)

        assert len(positions) == 7
        # QC positions from layout
        assert positions[0] == "B:F8"  # QC03dia
        assert positions[1] == "B:F9"  # QC01
        # User positions generated by sampler (Y plate, row A)
        assert positions[2] == "Y:A1"
        assert positions[3] == "Y:A2"
        assert positions[4] == "Y:A3"
        # End QCs
        assert positions[5] == "B:F7"  # clean
        assert positions[6] == "B:F9"  # QC01

    def test_mclass48_vial_proteomics(self):
        """MClass48 vial mode with proteomics QC layout."""
        # Typed MClass48 config
        config = GridSampler(
            description="MClass48 test",
            plates=["1", "2"],
            qc_plate="1",
            vial=GridContainer(
                container_type="Vial",
                position_source="generated",
                fill_order="row_major",
                position_format="{plate}:{row},{col}",
                sample_rows=["A", "B", "C", "D", "E"],
                cols=[1, 2, 3, 4, 5, 6, 7, 8],
            ),
        )
        generator = MClass48PositionGenerator(config, "vial")

        # Proteomics QC layout for MClass48
        qc_layout = {
            "QC01": "1:F,8",
            "QC03dia": "1:F,7",
            "clean": "1:F,6",
        }

        assigner = GeneratedPositionAssigner(sampler=generator, qc_layout=qc_layout)

        # Queue structure: start QCs, 3 user samples, end QCs
        structure = ["QC03dia", "QC01", "default", "default", "default", "clean", "QC01"]
        samples = [
            InputSample(sample_name="s1", sample_id=1),
            InputSample(sample_name="s2", sample_id=2),
            InputSample(sample_name="s3", sample_id=3),
        ]

        positions = assigner(structure, samples)

        assert len(positions) == 7
        # QC positions from layout
        assert positions[0] == "1:F,7"  # QC03dia
        assert positions[1] == "1:F,8"  # QC01
        # User positions generated by sampler (plate 2 since plate 1 is QC plate)
        assert positions[2] == "2:A,1"
        assert positions[3] == "2:A,2"
        assert positions[4] == "2:A,3"
        # End QCs
        assert positions[5] == "1:F,6"  # clean
        assert positions[6] == "1:F,8"  # QC01

    def test_evosep_vial_proteomics(self):
        """Evosep vial mode with proteomics QC layout."""
        # Typed Evosep config
        config = EvosepSampler(
            description="Evosep test",
            slots=[1, 2, 3, 4],
            positions_per_slot=96,
            vial=EvosepContainer(
                container_type="Vial",
                position_source="generated",
                fill_order="sequential",
            ),
        )
        generator = EvosepPositionGenerator(config, "vial")

        # Proteomics QC layout for Evosep (dict format)
        qc_layout = {
            "QC01": {"tray": 5, "position_start": 1, "position_end": 48},
            "QC03dia": {"tray": 5, "position_start": 49, "position_end": 96},
            "clean": {"tray": 6, "position_start": 1, "position_end": 96},
        }

        assigner = GeneratedPositionAssigner(sampler=generator, qc_layout=qc_layout)

        # Queue structure: start QCs, 3 user samples, end QCs
        structure = ["QC03dia", "QC01", "default", "default", "default", "clean", "QC01"]
        samples = [
            InputSample(sample_name="s1", sample_id=1),
            InputSample(sample_name="s2", sample_id=2),
            InputSample(sample_name="s3", sample_id=3),
        ]

        positions = assigner(structure, samples)

        assert len(positions) == 7
        # QC positions formatted as "tray{tray}:{position_start}"
        assert positions[0] == "tray5:49"  # QC03dia
        assert positions[1] == "tray5:1"  # QC01
        # User positions generated sequentially in tray 1
        assert positions[2] == "tray1:1"
        assert positions[3] == "tray1:2"
        assert positions[4] == "tray1:3"
        # End QCs
        assert positions[5] == "tray6:1"  # clean
        assert positions[6] == "tray5:1"  # QC01


class TestInputPositionAssigner:
    """Tests for InputPositionAssigner (plate mode)."""

    def test_vanquish_plate_metabolomics(self):
        """Vanquish plate mode with metabolomics QC layout."""
        # Metabolomics QC layout (from qc_layouts.toml)
        qc_layout = {
            "blank": "B:H1",
            "pooledQC": "B:H9",
            "108mix_AA": "B:H12",
        }

        assigner = InputPositionAssigner(qc_layout=qc_layout)

        # Simple structure: blank, 2 user samples, pooledQC
        structure = ["blank", "default", "default", "pooledQC"]
        samples = [
            InputSample(sample_name="s1", sample_id=1, grid_position="Y:A1"),
            InputSample(sample_name="s2", sample_id=2, grid_position="Y:A2"),
        ]

        positions = assigner(structure, samples)

        assert len(positions) == 4
        assert positions[0] == "B:H1"  # blank
        assert positions[1] == "Y:A1"  # from input
        assert positions[2] == "Y:A2"  # from input
        assert positions[3] == "B:H9"  # pooledQC

    def test_mclass48_plate_proteomics(self):
        """MClass48 plate mode with proteomics QC layout."""
        # Proteomics QC layout for MClass48 (from qc_layouts.toml)
        qc_layout = {
            "QC01": "1:F,8",
            "QC03dia": "1:F,7",
            "clean": "1:F,6",
        }

        assigner = InputPositionAssigner(qc_layout=qc_layout)

        # Structure: QC03dia, QC01, 2 user samples, clean
        structure = ["QC03dia", "QC01", "default", "default", "clean"]
        samples = [
            InputSample(sample_name="s1", sample_id=1, grid_position="1:A,1"),
            InputSample(sample_name="s2", sample_id=2, grid_position="1:A,2"),
        ]

        positions = assigner(structure, samples)

        assert len(positions) == 5
        assert positions[0] == "1:F,7"  # QC03dia
        assert positions[1] == "1:F,8"  # QC01
        assert positions[2] == "1:A,1"  # from input
        assert positions[3] == "1:A,2"  # from input
        assert positions[4] == "1:F,6"  # clean

    def test_evosep_plate_proteomics(self):
        """Evosep plate mode with proteomics QC layout (dict format)."""
        # Proteomics QC layout for Evosep (from qc_layouts.toml) - uses dict format
        qc_layout = {
            "QC01": {"tray": 5, "position_start": 1, "position_end": 48},
            "QC03dia": {"tray": 5, "position_start": 49, "position_end": 96},
            "clean": {"tray": 6, "position_start": 1, "position_end": 96},
        }

        assigner = InputPositionAssigner(qc_layout=qc_layout)

        # Structure: QC01, 2 user samples, clean
        structure = ["QC01", "default", "default", "clean"]
        samples = [
            InputSample(sample_name="s1", sample_id=1, grid_position="1"),
            InputSample(sample_name="s2", sample_id=2, grid_position="2"),
        ]

        positions = assigner(structure, samples)

        assert len(positions) == 4
        # Evosep QC positions formatted as "tray{tray}:{position_start}"
        assert positions[0] == "tray5:1"  # QC01
        assert positions[1] == "1"  # from input
        assert positions[2] == "2"  # from input
        assert positions[3] == "tray6:1"  # clean

    def test_raises_if_not_enough_samples(self):
        """Should raise ValueError if not enough input samples."""
        assigner = InputPositionAssigner(qc_layout={})

        structure = ["default", "default", "default"]
        samples = [
            InputSample(sample_name="s1", sample_id=1, grid_position="Y:A1"),
        ]

        with pytest.raises(ValueError, match="Not enough input samples"):
            assigner(structure, samples)


class TestCreatePositionAssigner:
    """Tests for create_position_assigner factory."""

    def test_creates_generated_assigner_for_vanquish_vial(self):
        """Vanquish.vial should create GeneratedPositionAssigner."""
        config = GridSampler(
            description="Vanquish test",
            plates=["Y", "R", "B", "G"],
            qc_plate="B",
            vial=GridContainer(
                container_type="Vial",
                position_source="generated",
                fill_order="row_major",
                position_format="{plate}:{row}{col}",
                sample_rows=["A", "B", "C", "D", "E"],
                cols=[1, 2, 3, 4, 5, 6, 7, 8, 9],
            ),
        )
        qc_layout = {"QC01": "B:F9"}

        assigner = create_position_assigner("Vanquish.vial", config, qc_layout)

        assert isinstance(assigner, GeneratedPositionAssigner)

    def test_creates_input_assigner_for_vanquish_plate(self):
        """Vanquish.plate should create InputPositionAssigner."""
        config = GridSampler(
            description="Vanquish test",
            plates=["Y", "R", "B", "G"],
            qc_plate="B",
            plate=GridContainer(
                container_type="Plate",
                position_source="input",
            ),
        )
        qc_layout = {"QC01": "B:H9"}

        assigner = create_position_assigner("Vanquish.plate", config, qc_layout)

        assert isinstance(assigner, InputPositionAssigner)

    def test_creates_input_assigner_for_mclass48_plate(self):
        """MClass48.plate should create InputPositionAssigner."""
        config = GridSampler(
            description="MClass48 test",
            plates=["1", "2"],
            qc_plate="1",
            plate=GridContainer(
                container_type="Plate",
                position_source="input",
            ),
        )
        qc_layout = {"QC01": "1:F,8"}

        assigner = create_position_assigner("MClass48.plate", config, qc_layout)

        assert isinstance(assigner, InputPositionAssigner)

    def test_creates_input_assigner_for_evosep_plate(self):
        """Evosep.plate should create InputPositionAssigner."""
        config = EvosepSampler(
            description="Evosep test",
            slots=[1, 2, 3, 4],
            positions_per_slot=96,
            plate=EvosepContainer(
                container_type="Plate",
                position_source="input",
            ),
        )
        qc_layout = {"QC01": {"tray": 5, "position_start": 1}}

        assigner = create_position_assigner("Evosep.plate", config, qc_layout)

        assert isinstance(assigner, InputPositionAssigner)

    def test_creates_generated_assigner_for_mclass48_vial(self):
        """MClass48.vial should create GeneratedPositionAssigner."""
        config = GridSampler(
            description="MClass48 test",
            plates=["1", "2"],
            qc_plate="1",
            vial=GridContainer(
                container_type="Vial",
                position_source="generated",
                fill_order="row_major",
                position_format="{plate}:{row},{col}",
                sample_rows=["A", "B", "C", "D", "E"],
                cols=[1, 2, 3, 4, 5, 6, 7, 8],
            ),
        )
        qc_layout = {"QC01": "1:F,8"}

        assigner = create_position_assigner("MClass48.vial", config, qc_layout)

        assert isinstance(assigner, GeneratedPositionAssigner)

    def test_creates_generated_assigner_for_evosep_vial(self):
        """Evosep.vial should create GeneratedPositionAssigner."""
        config = EvosepSampler(
            description="Evosep test",
            slots=[1, 2, 3, 4],
            positions_per_slot=96,
            vial=EvosepContainer(
                container_type="Vial",
                position_source="generated",
                fill_order="sequential",
            ),
        )
        qc_layout = {"QC01": {"tray": 5, "position_start": 1}}

        assigner = create_position_assigner("Evosep.vial", config, qc_layout)

        assert isinstance(assigner, GeneratedPositionAssigner)
