"""Tests for Sampler classes with different samplers and technologies."""

import pytest

from qg.config_models_samplers import (
    EvosepConfig,
    EvosepPlateConfig,
    EvosepVialConfig,
    MClass48Config,
    MClass48PlateConfig,
    MClass48VialConfig,
    SamplersConfig,
    VanquishConfig,
    VanquishPlateConfig,
    VanquishVialConfig,
)
from qg.params_models import InputSample
from qg.positions import (
    VanquishVialSampler,
    VanquishPlateSampler,
    MClass48VialSampler,
    MClass48PlateSampler,
    EvosepVialSampler,
    EvosepPlateSampler,
    create_sampler,
)


class TestVanquishVialSampler:
    """Tests for VanquishVialSampler (vial mode, generates positions)."""

    def test_proteomics_qc_layout(self):
        """Vanquish vial mode with proteomics QC layout."""
        # Typed Vanquish config
        parent = VanquishConfig(
            description="Vanquish test",
            plates=["Y", "R", "B", "G"],
            vial=VanquishVialConfig(
                position_format="{plate}:{row}{col}",
                sample_rows=["A", "B", "C", "D", "E"],
                cols=[1, 2, 3, 4, 5, 6, 7, 8, 9],
            ),
            plate=VanquishPlateConfig(
                position_format="{plate}:{grid_position}",
                sample_rows=["A", "B", "C", "D", "E", "F", "G"],
                cols=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
            ),
        )
        sampler = VanquishVialSampler(parent, parent.vial)

        # Proteomics QC layout (from qc_layouts.toml)
        qc_layout = {
            "QC01": "B:F9",
            "QC03dia": "B:F8",
            "clean": "B:F7",
        }

        # Queue structure: start QCs, 3 user samples, end QCs
        structure = ["QC03dia", "QC01", "default", "default", "default", "clean", "QC01"]
        samples = [
            InputSample(sample_name="s1", sample_id=1),
            InputSample(sample_name="s2", sample_id=2),
            InputSample(sample_name="s3", sample_id=3),
        ]

        positions = sampler.assign_positions(structure, samples, qc_layout)

        assert len(positions) == 7
        # QC positions from layout
        assert positions[0] == "B:F8"  # QC03dia
        assert positions[1] == "B:F9"  # QC01
        # User positions generated by sampler (Y plate, row A)
        assert positions[2] == "Y:A1"
        assert positions[3] == "Y:A2"
        assert positions[4] == "Y:A3"
        # End QCs
        assert positions[5] == "B:F7"  # clean
        assert positions[6] == "B:F9"  # QC01


class TestMClass48VialSampler:
    """Tests for MClass48VialSampler (vial mode, generates positions)."""

    def test_proteomics_qc_layout(self):
        """MClass48 vial mode with proteomics QC layout."""
        # Typed MClass48 config
        parent = MClass48Config(
            description="MClass48 test",
            plates=["1", "2"],
            sample_rows=["A", "B", "C", "D", "E"],
            cols=[1, 2, 3, 4, 5, 6, 7, 8],
            vial=MClass48VialConfig(
                position_format="{plate}:{row},{col}",
            ),
            plate=MClass48PlateConfig(
                position_format="{plate}:{grid_position}",
            ),
        )
        sampler = MClass48VialSampler(parent, parent.vial)

        # Proteomics QC layout for MClass48
        qc_layout = {
            "QC01": "1:F,8",
            "QC03dia": "1:F,7",
            "clean": "1:F,6",
        }

        # Queue structure: start QCs, 3 user samples, end QCs
        structure = ["QC03dia", "QC01", "default", "default", "default", "clean", "QC01"]
        samples = [
            InputSample(sample_name="s1", sample_id=1),
            InputSample(sample_name="s2", sample_id=2),
            InputSample(sample_name="s3", sample_id=3),
        ]

        positions = sampler.assign_positions(structure, samples, qc_layout)

        assert len(positions) == 7
        # QC positions from layout
        assert positions[0] == "1:F,7"  # QC03dia
        assert positions[1] == "1:F,8"  # QC01
        # User positions generated by sampler (plate 1, row A)
        assert positions[2] == "1:A,1"
        assert positions[3] == "1:A,2"
        assert positions[4] == "1:A,3"
        # End QCs
        assert positions[5] == "1:F,6"  # clean
        assert positions[6] == "1:F,8"  # QC01


class TestEvosepVialSampler:
    """Tests for EvosepVialSampler (vial mode, generates positions)."""

    def test_proteomics_qc_layout(self):
        """Evosep vial mode with proteomics QC layout."""
        # Typed Evosep config
        parent = EvosepConfig(
            description="Evosep test",
            slots=[1, 2, 3, 4],
            positions_per_slot=96,
            vial=EvosepVialConfig(),
            plate=EvosepPlateConfig(),
        )
        sampler = EvosepVialSampler(parent, parent.vial)

        # Proteomics QC layout for Evosep (dict format)
        qc_layout = {
            "QC01": {"tray": 5, "position_start": 1, "position_end": 48},
            "QC03dia": {"tray": 5, "position_start": 49, "position_end": 96},
            "clean": {"tray": 6, "position_start": 1, "position_end": 96},
        }

        # Queue structure: start QCs, 3 user samples, end QCs
        structure = ["QC03dia", "QC01", "default", "default", "default", "clean", "QC01"]
        samples = [
            InputSample(sample_name="s1", sample_id=1),
            InputSample(sample_name="s2", sample_id=2),
            InputSample(sample_name="s3", sample_id=3),
        ]

        positions = sampler.assign_positions(structure, samples, qc_layout)

        assert len(positions) == 7
        # QC positions formatted as "tray{tray}:{position_start}"
        assert positions[0] == "tray5:49"  # QC03dia
        assert positions[1] == "tray5:1"  # QC01
        # User positions generated sequentially in tray 1
        assert positions[2] == "tray1:1"
        assert positions[3] == "tray1:2"
        assert positions[4] == "tray1:3"
        # End QCs
        assert positions[5] == "tray6:1"  # clean
        assert positions[6] == "tray5:1"  # QC01


class TestVanquishPlateSampler:
    """Tests for VanquishPlateSampler (plate mode, uses input positions)."""

    def test_metabolomics_qc_layout(self):
        """Vanquish plate mode with metabolomics QC layout."""
        parent = VanquishConfig(
            description="Vanquish test",
            plates=["Y", "R", "B", "G"],
            vial=VanquishVialConfig(
                position_format="{plate}:{row}{col}",
                sample_rows=["A", "B", "C", "D", "E"],
                cols=[1, 2, 3, 4, 5, 6, 7, 8, 9],
            ),
            plate=VanquishPlateConfig(
                position_format="{plate}:{grid_position}",
                sample_rows=["A", "B", "C", "D", "E", "F", "G"],
                cols=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
            ),
        )
        sampler = VanquishPlateSampler(parent, parent.plate)

        # Metabolomics QC layout (from qc_layouts.toml)
        qc_layout = {
            "blank": "B:H1",
            "pooledQC": "B:H9",
            "108mix_AA": "B:H12",
        }

        # Simple structure: blank, 2 user samples, pooledQC
        structure = ["blank", "default", "default", "pooledQC"]
        samples = [
            InputSample(sample_name="s1", sample_id=1, grid_position="Y:A1"),
            InputSample(sample_name="s2", sample_id=2, grid_position="Y:A2"),
        ]

        positions = sampler.assign_positions(structure, samples, qc_layout)

        assert len(positions) == 4
        assert positions[0] == "B:H1"  # blank
        assert positions[1] == "Y:A1"  # from input
        assert positions[2] == "Y:A2"  # from input
        assert positions[3] == "B:H9"  # pooledQC


class TestMClass48PlateSampler:
    """Tests for MClass48PlateSampler (plate mode, uses input positions)."""

    def test_proteomics_qc_layout(self):
        """MClass48 plate mode with proteomics QC layout."""
        parent = MClass48Config(
            description="MClass48 test",
            plates=["1", "2"],
            sample_rows=["A", "B", "C", "D", "E"],
            cols=[1, 2, 3, 4, 5, 6, 7, 8],
            vial=MClass48VialConfig(
                position_format="{plate}:{row},{col}",
            ),
            plate=MClass48PlateConfig(
                position_format="{plate}:{grid_position}",
            ),
        )
        sampler = MClass48PlateSampler(parent, parent.plate)

        # Proteomics QC layout for MClass48 (from qc_layouts.toml)
        qc_layout = {
            "QC01": "1:F,8",
            "QC03dia": "1:F,7",
            "clean": "1:F,6",
        }

        # Structure: QC03dia, QC01, 2 user samples, clean
        structure = ["QC03dia", "QC01", "default", "default", "clean"]
        samples = [
            InputSample(sample_name="s1", sample_id=1, grid_position="1:A,1"),
            InputSample(sample_name="s2", sample_id=2, grid_position="1:A,2"),
        ]

        positions = sampler.assign_positions(structure, samples, qc_layout)

        assert len(positions) == 5
        assert positions[0] == "1:F,7"  # QC03dia
        assert positions[1] == "1:F,8"  # QC01
        assert positions[2] == "1:A,1"  # from input
        assert positions[3] == "1:A,2"  # from input
        assert positions[4] == "1:F,6"  # clean


class TestEvosepPlateSampler:
    """Tests for EvosepPlateSampler (plate mode, uses input positions)."""

    def test_proteomics_qc_layout(self):
        """Evosep plate mode with proteomics QC layout (dict format)."""
        parent = EvosepConfig(
            description="Evosep test",
            slots=[1, 2, 3, 4],
            positions_per_slot=96,
            vial=EvosepVialConfig(),
            plate=EvosepPlateConfig(),
        )
        sampler = EvosepPlateSampler(parent, parent.plate)

        # Proteomics QC layout for Evosep (from qc_layouts.toml) - uses dict format
        qc_layout = {
            "QC01": {"tray": 5, "position_start": 1, "position_end": 48},
            "QC03dia": {"tray": 5, "position_start": 49, "position_end": 96},
            "clean": {"tray": 6, "position_start": 1, "position_end": 96},
        }

        # Structure: QC01, 2 user samples, clean
        structure = ["QC01", "default", "default", "clean"]
        samples = [
            InputSample(sample_name="s1", sample_id=1, grid_position="1"),
            InputSample(sample_name="s2", sample_id=2, grid_position="2"),
        ]

        positions = sampler.assign_positions(structure, samples, qc_layout)

        assert len(positions) == 4
        # Evosep QC positions formatted as "tray{tray}:{position_start}"
        assert positions[0] == "tray5:1"  # QC01
        assert positions[1] == "1"  # from input
        assert positions[2] == "2"  # from input
        assert positions[3] == "tray6:1"  # clean

    def test_raises_if_not_enough_samples(self):
        """Should raise ValueError if not enough input samples."""
        parent = EvosepConfig(
            description="Evosep test",
            slots=[1, 2, 3, 4],
            positions_per_slot=96,
            vial=EvosepVialConfig(),
            plate=EvosepPlateConfig(),
        )
        sampler = EvosepPlateSampler(parent, parent.plate)

        structure = ["default", "default", "default"]
        samples = [
            InputSample(sample_name="s1", sample_id=1, grid_position="Y:A1"),
        ]

        with pytest.raises(ValueError, match="Not enough input samples"):
            sampler.assign_positions(structure, samples, {})


class TestCreateSampler:
    """Tests for create_sampler factory."""

    @pytest.fixture
    def samplers_config(self):
        """Create a complete SamplersConfig for testing."""
        return SamplersConfig(
            Vanquish=VanquishConfig(
                description="Vanquish test",
                plates=["Y", "R", "B", "G"],
                vial=VanquishVialConfig(
                    position_format="{plate}:{row}{col}",
                    sample_rows=["A", "B", "C", "D", "E"],
                    cols=[1, 2, 3, 4, 5, 6, 7, 8, 9],
                ),
                plate=VanquishPlateConfig(
                    position_format="{plate}:{grid_position}",
                    sample_rows=["A", "B", "C", "D", "E", "F", "G"],
                    cols=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                ),
            ),
            MClass48=MClass48Config(
                description="MClass48 test",
                plates=["1", "2"],
                sample_rows=["A", "B", "C", "D", "E"],
                cols=[1, 2, 3, 4, 5, 6, 7, 8],
                vial=MClass48VialConfig(
                    position_format="{plate}:{row},{col}",
                ),
                plate=MClass48PlateConfig(
                    position_format="{plate}:{grid_position}",
                ),
            ),
            Evosep=EvosepConfig(
                description="Evosep test",
                slots=[1, 2, 3, 4],
                positions_per_slot=96,
                vial=EvosepVialConfig(),
                plate=EvosepPlateConfig(),
            ),
        )

    def test_creates_vanquish_vial_sampler(self, samplers_config):
        """Vanquish.vial should create VanquishVialSampler."""
        sampler = create_sampler("Vanquish.vial", samplers_config)
        assert isinstance(sampler, VanquishVialSampler)

    def test_creates_vanquish_plate_sampler(self, samplers_config):
        """Vanquish.plate should create VanquishPlateSampler."""
        sampler = create_sampler("Vanquish.plate", samplers_config)
        assert isinstance(sampler, VanquishPlateSampler)

    def test_creates_mclass48_vial_sampler(self, samplers_config):
        """MClass48.vial should create MClass48VialSampler."""
        sampler = create_sampler("MClass48.vial", samplers_config)
        assert isinstance(sampler, MClass48VialSampler)

    def test_creates_mclass48_plate_sampler(self, samplers_config):
        """MClass48.plate should create MClass48PlateSampler."""
        sampler = create_sampler("MClass48.plate", samplers_config)
        assert isinstance(sampler, MClass48PlateSampler)

    def test_creates_evosep_vial_sampler(self, samplers_config):
        """Evosep.vial should create EvosepVialSampler."""
        sampler = create_sampler("Evosep.vial", samplers_config)
        assert isinstance(sampler, EvosepVialSampler)

    def test_creates_evosep_plate_sampler(self, samplers_config):
        """Evosep.plate should create EvosepPlateSampler."""
        sampler = create_sampler("Evosep.plate", samplers_config)
        assert isinstance(sampler, EvosepPlateSampler)

    def test_raises_for_unknown_sampler(self, samplers_config):
        """Should raise ValueError for unknown sampler."""
        with pytest.raises(ValueError, match="Unknown sampler"):
            create_sampler("Unknown.vial", samplers_config)
