"""Tests for Sampler classes with different samplers and technologies."""

import pytest

from qg.config_models_samplers import (
    EvosepConfig,
    EvosepPlateConfig,
    EvosepVialConfig,
    MClass48Config,
    MClass48PlateConfig,
    MClass48VialConfig,
    SamplersConfig,
    VanquishConfig,
    VanquishPlateConfig,
    VanquishVialConfig,
)
from qg.params_models import InputSample
from qg.positions import (
    VanquishVialSampler,
    VanquishPlateSampler,
    MClass48VialSampler,
    MClass48PlateSampler,
    EvosepVialSampler,
    EvosepPlateSampler,
    create_sampler,
    QCLayoutPattern,
)


class TestVanquishVialSampler:
    """Tests for VanquishVialSampler (vial mode, generates positions)."""

    def test_proteomics_qc_layout(self):
        """Vanquish vial mode with proteomics QC layout."""
        # Typed Vanquish config
        parent = VanquishConfig(
            description="Vanquish test",
            plates=["Y", "R", "B", "G"],
            vial=VanquishVialConfig(
                position_format="{plate}:{row}{col}",
                sample_rows=["A", "B", "C", "D", "E"],
                cols=[1, 2, 3, 4, 5, 6, 7, 8, 9],
            ),
            plate=VanquishPlateConfig(
                position_format="{plate}:{grid_position}",
                sample_rows=["A", "B", "C", "D", "E", "F", "G"],
                cols=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
            ),
        )

        # QC layout pattern with pre-formatted positions
        qc_layout_pattern = QCLayoutPattern(positions={
            "QC01": "B:F9",
            "QC03dia": "B:F8",
            "clean": "B:F7",
        })
        sampler = VanquishVialSampler(parent, parent.vial, qc_layout_pattern)

        # Queue structure: start QCs, 3 user samples, end QCs
        structure = ["QC03dia", "QC01", "default", "default", "default", "clean", "QC01"]
        samples = [
            InputSample(sample_name="s1", sample_id=1),
            InputSample(sample_name="s2", sample_id=2),
            InputSample(sample_name="s3", sample_id=3),
        ]

        positions = sampler.assign_positions(structure, samples)

        assert len(positions) == 7
        # QC positions from layout
        assert positions[0] == "B:F8"  # QC03dia
        assert positions[1] == "B:F9"  # QC01
        # User positions generated by sampler (Y plate, row A)
        assert positions[2] == "Y:A1"
        assert positions[3] == "Y:A2"
        assert positions[4] == "Y:A3"
        # End QCs
        assert positions[5] == "B:F7"  # clean
        assert positions[6] == "B:F9"  # QC01


class TestMClass48VialSampler:
    """Tests for MClass48VialSampler (vial mode, generates positions)."""

    def test_proteomics_qc_layout(self):
        """MClass48 vial mode with proteomics QC layout."""
        # Typed MClass48 config
        parent = MClass48Config(
            description="MClass48 test",
            plates=["1", "2"],
            sample_rows=["A", "B", "C", "D", "E"],
            cols=[1, 2, 3, 4, 5, 6, 7, 8],
            vial=MClass48VialConfig(
                position_format="{plate}:{row},{col}",
            ),
            plate=MClass48PlateConfig(
                position_format="{plate}:{grid_position}",
            ),
        )

        # QC layout pattern with pre-formatted positions
        qc_layout_pattern = QCLayoutPattern(positions={
            "QC01": "1:F,8",
            "QC03dia": "1:F,7",
            "clean": "1:F,6",
        })
        sampler = MClass48VialSampler(parent, parent.vial, qc_layout_pattern)

        # Queue structure: start QCs, 3 user samples, end QCs
        structure = ["QC03dia", "QC01", "default", "default", "default", "clean", "QC01"]
        samples = [
            InputSample(sample_name="s1", sample_id=1),
            InputSample(sample_name="s2", sample_id=2),
            InputSample(sample_name="s3", sample_id=3),
        ]

        positions = sampler.assign_positions(structure, samples)

        assert len(positions) == 7
        # QC positions from layout
        assert positions[0] == "1:F,7"  # QC03dia
        assert positions[1] == "1:F,8"  # QC01
        # User positions generated by sampler (plate 1, row A)
        assert positions[2] == "1:A,1"
        assert positions[3] == "1:A,2"
        assert positions[4] == "1:A,3"
        # End QCs
        assert positions[5] == "1:F,6"  # clean
        assert positions[6] == "1:F,8"  # QC01


class TestEvosepVialSampler:
    """Tests for EvosepVialSampler (vial mode, generates positions)."""

    def test_proteomics_qc_layout(self):
        """Evosep vial mode with proteomics QC layout."""
        # Typed Evosep config
        parent = EvosepConfig(
            description="Evosep test",
            slots=[1, 2, 3, 4],
            positions_per_slot=96,
            vial=EvosepVialConfig(),
            plate=EvosepPlateConfig(),
        )

        # QC layout pattern with pre-formatted positions (Evosep format)
        qc_layout_pattern = QCLayoutPattern(positions={
            "QC01": "tray5:1",
            "QC03dia": "tray5:49",
            "clean": "tray6:1",
        })
        sampler = EvosepVialSampler(parent, parent.vial, qc_layout_pattern)

        # Queue structure: start QCs, 3 user samples, end QCs
        structure = ["QC03dia", "QC01", "default", "default", "default", "clean", "QC01"]
        samples = [
            InputSample(sample_name="s1", sample_id=1),
            InputSample(sample_name="s2", sample_id=2),
            InputSample(sample_name="s3", sample_id=3),
        ]

        positions = sampler.assign_positions(structure, samples)

        assert len(positions) == 7
        # QC positions formatted as "tray{tray}:{position_start}"
        assert positions[0] == "tray5:49"  # QC03dia
        assert positions[1] == "tray5:1"  # QC01
        # User positions generated sequentially in tray 1
        assert positions[2] == "tray1:1"
        assert positions[3] == "tray1:2"
        assert positions[4] == "tray1:3"
        # End QCs
        assert positions[5] == "tray6:1"  # clean
        assert positions[6] == "tray5:1"  # QC01


class TestVanquishPlateSampler:
    """Tests for VanquishPlateSampler (plate mode, uses input positions)."""

    def test_metabolomics_qc_layout(self):
        """Vanquish plate mode with metabolomics QC layout."""
        parent = VanquishConfig(
            description="Vanquish test",
            plates=["Y", "R", "B", "G"],
            vial=VanquishVialConfig(
                position_format="{plate}:{row}{col}",
                sample_rows=["A", "B", "C", "D", "E"],
                cols=[1, 2, 3, 4, 5, 6, 7, 8, 9],
            ),
            plate=VanquishPlateConfig(
                position_format="{plate}:{grid_position}",
                sample_rows=["A", "B", "C", "D", "E", "F", "G"],
                cols=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
            ),
        )

        # QC layout pattern with pre-formatted positions
        qc_layout_pattern = QCLayoutPattern(positions={
            "blank": "B:H1",
            "pooledQC": "B:H9",
            "108mix_AA": "B:H12",
        })
        sampler = VanquishPlateSampler(parent, parent.plate, qc_layout_pattern)

        # Simple structure: blank, 2 user samples, pooledQC
        structure = ["blank", "default", "default", "pooledQC"]
        samples = [
            InputSample(sample_name="s1", sample_id=1, grid_position="Y:A1"),
            InputSample(sample_name="s2", sample_id=2, grid_position="Y:A2"),
        ]

        positions = sampler.assign_positions(structure, samples)

        assert len(positions) == 4
        assert positions[0] == "B:H1"  # blank
        assert positions[1] == "Y:A1"  # from input
        assert positions[2] == "Y:A2"  # from input
        assert positions[3] == "B:H9"  # pooledQC


class TestMClass48PlateSampler:
    """Tests for MClass48PlateSampler (plate mode, uses input positions)."""

    def test_proteomics_qc_layout(self):
        """MClass48 plate mode with proteomics QC layout."""
        parent = MClass48Config(
            description="MClass48 test",
            plates=["1", "2"],
            sample_rows=["A", "B", "C", "D", "E"],
            cols=[1, 2, 3, 4, 5, 6, 7, 8],
            vial=MClass48VialConfig(
                position_format="{plate}:{row},{col}",
            ),
            plate=MClass48PlateConfig(
                position_format="{plate}:{grid_position}",
            ),
        )

        # QC layout pattern with pre-formatted positions
        qc_layout_pattern = QCLayoutPattern(positions={
            "QC01": "1:F,8",
            "QC03dia": "1:F,7",
            "clean": "1:F,6",
        })
        sampler = MClass48PlateSampler(parent, parent.plate, qc_layout_pattern)

        # Structure: QC03dia, QC01, 2 user samples, clean
        structure = ["QC03dia", "QC01", "default", "default", "clean"]
        samples = [
            InputSample(sample_name="s1", sample_id=1, grid_position="1:A,1"),
            InputSample(sample_name="s2", sample_id=2, grid_position="1:A,2"),
        ]

        positions = sampler.assign_positions(structure, samples)

        assert len(positions) == 5
        assert positions[0] == "1:F,7"  # QC03dia
        assert positions[1] == "1:F,8"  # QC01
        assert positions[2] == "1:A,1"  # from input
        assert positions[3] == "1:A,2"  # from input
        assert positions[4] == "1:F,6"  # clean


class TestEvosepPlateSampler:
    """Tests for EvosepPlateSampler (plate mode, uses input positions)."""

    def test_proteomics_qc_layout(self):
        """Evosep plate mode with proteomics QC layout (dict format)."""
        parent = EvosepConfig(
            description="Evosep test",
            slots=[1, 2, 3, 4],
            positions_per_slot=96,
            vial=EvosepVialConfig(),
            plate=EvosepPlateConfig(),
        )

        # QC layout pattern with pre-formatted positions (Evosep format)
        qc_layout_pattern = QCLayoutPattern(positions={
            "QC01": "tray5:1",
            "QC03dia": "tray5:49",
            "clean": "tray6:1",
        })
        sampler = EvosepPlateSampler(parent, parent.plate, qc_layout_pattern)

        # Structure: QC01, 2 user samples, clean
        structure = ["QC01", "default", "default", "clean"]
        samples = [
            InputSample(sample_name="s1", sample_id=1, grid_position="1"),
            InputSample(sample_name="s2", sample_id=2, grid_position="2"),
        ]

        positions = sampler.assign_positions(structure, samples)

        assert len(positions) == 4
        # Evosep QC positions formatted as "tray{tray}:{position_start}"
        assert positions[0] == "tray5:1"  # QC01
        assert positions[1] == "1"  # from input
        assert positions[2] == "2"  # from input
        assert positions[3] == "tray6:1"  # clean

    def test_raises_if_not_enough_samples(self):
        """Should raise ValueError if not enough input samples."""
        parent = EvosepConfig(
            description="Evosep test",
            slots=[1, 2, 3, 4],
            positions_per_slot=96,
            vial=EvosepVialConfig(),
            plate=EvosepPlateConfig(),
        )

        # Empty QC layout pattern for this test
        qc_layout_pattern = QCLayoutPattern(positions={})
        sampler = EvosepPlateSampler(parent, parent.plate, qc_layout_pattern)

        structure = ["default", "default", "default"]
        samples = [
            InputSample(sample_name="s1", sample_id=1, grid_position="Y:A1"),
        ]

        with pytest.raises(ValueError, match="Not enough input samples"):
            sampler.assign_positions(structure, samples)


class TestCreateSampler:
    """Tests for create_sampler factory."""

    @pytest.fixture
    def samplers_config(self):
        """Create a complete SamplersConfig for testing."""
        return SamplersConfig(
            Vanquish=VanquishConfig(
                description="Vanquish test",
                plates=["Y", "R", "B", "G"],
                vial=VanquishVialConfig(
                    position_format="{plate}:{row}{col}",
                    sample_rows=["A", "B", "C", "D", "E"],
                    cols=[1, 2, 3, 4, 5, 6, 7, 8, 9],
                ),
                plate=VanquishPlateConfig(
                    position_format="{plate}:{grid_position}",
                    sample_rows=["A", "B", "C", "D", "E", "F", "G"],
                    cols=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                ),
            ),
            MClass48=MClass48Config(
                description="MClass48 test",
                plates=["1", "2"],
                sample_rows=["A", "B", "C", "D", "E"],
                cols=[1, 2, 3, 4, 5, 6, 7, 8],
                vial=MClass48VialConfig(
                    position_format="{plate}:{row},{col}",
                ),
                plate=MClass48PlateConfig(
                    position_format="{plate}:{grid_position}",
                ),
            ),
            Evosep=EvosepConfig(
                description="Evosep test",
                slots=[1, 2, 3, 4],
                positions_per_slot=96,
                vial=EvosepVialConfig(),
                plate=EvosepPlateConfig(),
            ),
        )

    @pytest.fixture
    def qc_layout_pattern(self):
        """Create a QCLayoutPattern for testing."""
        return QCLayoutPattern(positions={
            "QC01": "B:F9",
            "QC03dia": "B:F8",
            "clean": "B:F7",
        })

    def test_creates_vanquish_vial_sampler(self, samplers_config, qc_layout_pattern):
        """Vanquish.vial should create VanquishVialSampler."""
        sampler = create_sampler("Vanquish.vial", samplers_config, qc_layout_pattern)
        assert isinstance(sampler, VanquishVialSampler)

    def test_creates_vanquish_plate_sampler(self, samplers_config, qc_layout_pattern):
        """Vanquish.plate should create VanquishPlateSampler."""
        sampler = create_sampler("Vanquish.plate", samplers_config, qc_layout_pattern)
        assert isinstance(sampler, VanquishPlateSampler)

    def test_creates_mclass48_vial_sampler(self, samplers_config, qc_layout_pattern):
        """MClass48.vial should create MClass48VialSampler."""
        sampler = create_sampler("MClass48.vial", samplers_config, qc_layout_pattern)
        assert isinstance(sampler, MClass48VialSampler)

    def test_creates_mclass48_plate_sampler(self, samplers_config, qc_layout_pattern):
        """MClass48.plate should create MClass48PlateSampler."""
        sampler = create_sampler("MClass48.plate", samplers_config, qc_layout_pattern)
        assert isinstance(sampler, MClass48PlateSampler)

    def test_creates_evosep_vial_sampler(self, samplers_config, qc_layout_pattern):
        """Evosep.vial should create EvosepVialSampler."""
        sampler = create_sampler("Evosep.vial", samplers_config, qc_layout_pattern)
        assert isinstance(sampler, EvosepVialSampler)

    def test_creates_evosep_plate_sampler(self, samplers_config, qc_layout_pattern):
        """Evosep.plate should create EvosepPlateSampler."""
        sampler = create_sampler("Evosep.plate", samplers_config, qc_layout_pattern)
        assert isinstance(sampler, EvosepPlateSampler)

    def test_raises_for_unknown_sampler(self, samplers_config, qc_layout_pattern):
        """Should raise ValueError for unknown sampler."""
        with pytest.raises(ValueError, match="Unknown sampler"):
            create_sampler("Unknown.vial", samplers_config, qc_layout_pattern)


class TestQCLayoutPattern:
    """Tests for QCLayoutPattern validation."""

    def test_create_from_pattern_and_layout(self):
        """Should create QCLayoutPattern from pattern and qc_layout."""
        from qg.config_models import QueuePattern

        pattern = QueuePattern(
            description="Test pattern",
            run_QC_after_n_samples=5,
            start=["QC01"],
            middle=["QC01"],
            end=["clean"],
        )
        qc_layout = {
            "QC01": "B:F9",
            "clean": "B:F7",
        }

        qc_layout_pattern = QCLayoutPattern.create(pattern, qc_layout)

        assert qc_layout_pattern.positions == {"QC01": "B:F9", "clean": "B:F7"}
        assert qc_layout_pattern.get_position("QC01") == "B:F9"
        assert qc_layout_pattern.get_position("clean") == "B:F7"
        assert qc_layout_pattern.get_position("unknown") == ""

    def test_raises_if_qc_sample_not_in_layout(self):
        """Should raise ValueError if pattern references QC not in layout."""
        from qg.config_models import QueuePattern

        pattern = QueuePattern(
            description="Test pattern",
            run_QC_after_n_samples=5,
            start=["QC01", "missing_qc"],
            middle=[],
            end=[],
        )
        qc_layout = {"QC01": "B:F9"}

        with pytest.raises(ValueError, match="QC sample 'missing_qc' not in qc_layout"):
            QCLayoutPattern.create(pattern, qc_layout)

    def test_raises_if_positions_conflict(self):
        """Should raise ValueError if two QC samples have same position."""
        from qg.config_models import QueuePattern

        pattern = QueuePattern(
            description="Test pattern",
            run_QC_after_n_samples=5,
            start=["QC01", "QC02"],  # Both used in pattern
            middle=[],
            end=[],
        )
        # Both QC samples map to the same position - this is the conflict
        qc_layout = {
            "QC01": "B:F9",
            "QC02": "B:F9",  # Same position as QC01!
        }

        with pytest.raises(ValueError, match="Position conflict"):
            QCLayoutPattern.create(pattern, qc_layout)

    def test_no_conflict_for_unused_duplicate_positions(self):
        """Position duplicates are OK if only one is used in pattern."""
        from qg.config_models import QueuePattern

        pattern = QueuePattern(
            description="Test pattern",
            run_QC_after_n_samples=5,
            start=["QC01"],
            middle=[],
            end=[],
        )
        # QC02 has same position as QC01 but it's not used in pattern
        qc_layout = {
            "QC01": "B:F9",
            "QC02": "B:F9",  # Same position, but QC02 not used
        }

        # Should not raise - only QC01 is used
        qc_layout_pattern = QCLayoutPattern.create(pattern, qc_layout)
        assert qc_layout_pattern.positions == {"QC01": "B:F9"}

    def test_collects_from_all_pattern_sections(self):
        """Should collect QC IDs from start, middle, end, separation, middle_extended."""
        from qg.config_models import QueuePattern

        pattern = QueuePattern(
            description="Test pattern",
            run_QC_after_n_samples=5,
            start=["qc_start"],
            middle=["qc_middle"],
            end=["qc_end"],
            separation=["qc_sep"],
            middle_extended=["qc_ext"],
        )
        qc_layout = {
            "qc_start": "A:1",
            "qc_middle": "A:2",
            "qc_end": "A:3",
            "qc_sep": "A:4",
            "qc_ext": "A:5",
        }

        qc_layout_pattern = QCLayoutPattern.create(pattern, qc_layout)

        # All 5 should be collected
        assert len(qc_layout_pattern.positions) == 5
        assert qc_layout_pattern.get_position("qc_start") == "A:1"
        assert qc_layout_pattern.get_position("qc_middle") == "A:2"
        assert qc_layout_pattern.get_position("qc_end") == "A:3"
        assert qc_layout_pattern.get_position("qc_sep") == "A:4"
        assert qc_layout_pattern.get_position("qc_ext") == "A:5"

    def test_formats_evosep_positions(self):
        """Should format Evosep dict positions correctly."""
        from qg.config_models import QueuePattern, EvosepPosition

        pattern = QueuePattern(
            description="Test pattern",
            run_QC_after_n_samples=5,
            start=["QC01"],
            middle=[],
            end=[],
        )
        qc_layout = {
            "QC01": EvosepPosition(tray=5, position_start=1, position_end=48),
        }

        qc_layout_pattern = QCLayoutPattern.create(pattern, qc_layout)

        assert qc_layout_pattern.get_position("QC01") == "tray5:1"
