"""Strategy protocols and implementations for pipeline steps.

Strategies are stateless callables that implement specific pipeline behaviors.
The generator can be parameterized with different strategy implementations.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol, Sequence

from qg.config_models import QCPosition
from qg.config_models_samplers import EvosepSampler, GridSampler
from qg.params_models import InputSample
from qg.positions import SamplerPositionGenerator, get_position_generator


# =============================================================================
# Position Assigner (merged user positions + QC positions)
# =============================================================================


def _merge_positions(
    structure: list[str],
    user_positions: list[str],
    qc_layout: dict[str, QCPosition],
) -> list[str]:
    """Merge user positions with QC positions based on structure."""
    positions = []
    user_idx = 0

    for sample_id in structure:
        if sample_id == "default":
            positions.append(user_positions[user_idx])
            user_idx += 1
        else:
            pos = qc_layout.get(sample_id, "")
            if isinstance(pos, dict):
                positions.append(
                    f"tray{pos.get('tray', 0)}:{pos.get('position_start', 0)}"
                )
            else:
                positions.append(str(pos))

    return positions


class PositionAssigner(Protocol):
    """Protocol for assigning positions to all slots in a queue structure.

    Combines user position generation/extraction with QC position lookup.
    """

    def __call__(
        self,
        structure: list[str],
        samples: Sequence[InputSample],
    ) -> list[str]:
        """Assign positions to all slots in the structure.

        Args:
            structure: List of sample IDs ("default" for user, QC IDs for QC)
            samples: Input samples (used for input-based position extraction)

        Returns:
            List of position strings, same length as structure
        """
        ...


@dataclass(frozen=True, slots=True)
class GeneratedPositionAssigner:
    """Position assigner that generates user positions algorithmically.

    For vial mode: user positions are generated by sampler.
    QC positions come from qc_layout.
    """

    sampler: SamplerPositionGenerator
    qc_layout: dict[str, QCPosition]

    def __call__(
        self,
        structure: list[str],
        samples: Sequence[InputSample],
    ) -> list[str]:
        """Generate user positions, merge with QC positions."""
        num_user = structure.count("default")
        user_positions = self.sampler.generate_positions(num_user)
        return _merge_positions(structure, user_positions, self.qc_layout)


@dataclass(frozen=True, slots=True)
class InputPositionAssigner:
    """Position assigner that extracts user positions from input samples.

    For plate mode: user positions come from B-Fabric input (grid_position).
    QC positions come from qc_layout.
    """

    qc_layout: dict[str, QCPosition]

    def __call__(
        self,
        structure: list[str],
        samples: Sequence[InputSample],
    ) -> list[str]:
        """Extract user positions from samples, merge with QC positions."""
        num_user = structure.count("default")

        if len(samples) < num_user:
            raise ValueError(
                f"Not enough input samples ({len(samples)}) for {num_user} positions"
            )

        user_positions = [s.grid_position or "" for s in samples[:num_user]]
        return _merge_positions(structure, user_positions, self.qc_layout)


def create_position_assigner(
    sampler_name: str,
    sampler_config: GridSampler | EvosepSampler,
    qc_layout: dict[str, QCPosition],
    position_format_override: str | None = None,
) -> PositionAssigner:
    """Factory function to create the appropriate position assigner.

    Args:
        sampler_name: Full sampler name like "Vanquish.vial"
        sampler_config: Typed sampler configuration model
        qc_layout: QC positions for this technology/sampler
        position_format_override: Optional position format to override sampler default

    Returns:
        Position assigner callable
    """
    # Extract container name to check position_source
    parts = sampler_name.split(".")
    container = parts[1] if len(parts) > 1 else "vial"
    container_config = getattr(sampler_config, container)

    if container_config is None:
        raise ValueError(f"Container '{container}' not defined for {parts[0]}")

    position_source = container_config.position_source

    if position_source == "generated":
        generator = get_position_generator(
            sampler_name, sampler_config, position_format_override
        )
        return GeneratedPositionAssigner(sampler=generator, qc_layout=qc_layout)
    else:
        return InputPositionAssigner(qc_layout=qc_layout)


