"""Strategy protocols and implementations for pipeline steps.

Strategies are stateless callables that implement specific pipeline behaviors.
The generator can be parameterized with different strategy implementations.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Protocol, Sequence

from qg.config_models import QCPosition
from qg.params_models import InputSample
from qg.positions import SamplerPositionGenerator, get_sampler


# =============================================================================
# Position Assigner (merged user positions + QC positions)
# =============================================================================


class PositionAssigner(Protocol):
    """Protocol for assigning positions to all slots in a queue structure.

    Combines user position generation/extraction with QC position lookup.
    """

    def __call__(
        self,
        structure: list[str],
        samples: Sequence[InputSample],
    ) -> list[str]:
        """Assign positions to all slots in the structure.

        Args:
            structure: List of sample IDs ("default" for user, QC IDs for QC)
            samples: Input samples (used for input-based position extraction)

        Returns:
            List of position strings, same length as structure
        """
        ...


@dataclass(frozen=True, slots=True)
class GeneratedPositionAssigner:
    """Position assigner that generates user positions algorithmically.

    For vial mode: user positions are generated by sampler.
    QC positions come from qc_layout.
    """

    sampler: SamplerPositionGenerator
    qc_layout: dict[str, QCPosition]

    def __call__(
        self,
        structure: list[str],
        samples: Sequence[InputSample],
    ) -> list[str]:
        """Generate user positions, merge with QC positions."""
        # Count user slots
        num_user = structure.count("default")

        # Generate user positions
        user_positions = self.sampler.generate_positions(num_user)

        # Merge into full position list
        return self._merge_positions(structure, user_positions)

    def _merge_positions(
        self, structure: list[str], user_positions: list[str]
    ) -> list[str]:
        """Merge user positions with QC positions based on structure."""
        positions = []
        user_idx = 0

        for sample_id in structure:
            if sample_id == "default":
                positions.append(user_positions[user_idx])
                user_idx += 1
            else:
                pos = self.qc_layout.get(sample_id, "")
                if isinstance(pos, dict):
                    positions.append(
                        f"tray{pos.get('tray', 0)}:{pos.get('position_start', 0)}"
                    )
                else:
                    positions.append(str(pos))

        return positions


@dataclass(frozen=True, slots=True)
class InputPositionAssigner:
    """Position assigner that extracts user positions from input samples.

    For plate mode: user positions come from B-Fabric input (grid_position).
    QC positions come from qc_layout.
    """

    qc_layout: dict[str, QCPosition]

    def __call__(
        self,
        structure: list[str],
        samples: Sequence[InputSample],
    ) -> list[str]:
        """Extract user positions from samples, merge with QC positions."""
        # Count user slots
        num_user = structure.count("default")

        if len(samples) < num_user:
            raise ValueError(
                f"Not enough input samples ({len(samples)}) for {num_user} positions"
            )

        # Extract user positions from samples
        user_positions = [s.grid_position or "" for s in samples[:num_user]]

        # Merge into full position list
        return self._merge_positions(structure, user_positions)

    def _merge_positions(
        self, structure: list[str], user_positions: list[str]
    ) -> list[str]:
        """Merge user positions with QC positions based on structure."""
        positions = []
        user_idx = 0

        for sample_id in structure:
            if sample_id == "default":
                positions.append(user_positions[user_idx])
                user_idx += 1
            else:
                pos = self.qc_layout.get(sample_id, "")
                if isinstance(pos, dict):
                    positions.append(
                        f"tray{pos.get('tray', 0)}:{pos.get('position_start', 0)}"
                    )
                else:
                    positions.append(str(pos))

        return positions


def create_position_assigner(
    sampler_name: str,
    sampler_config: dict,
    qc_layout: dict[str, QCPosition],
) -> PositionAssigner:
    """Factory function to create the appropriate position assigner.

    Args:
        sampler_name: Full sampler name like "Vanquish.vial"
        sampler_config: Merged sampler configuration dict
        qc_layout: QC positions for this technology/sampler

    Returns:
        Position assigner callable
    """
    position_source = sampler_config.get("position_source", "generated")

    if position_source == "generated":
        sampler = get_sampler(sampler_name, sampler_config)
        return GeneratedPositionAssigner(sampler=sampler, qc_layout=qc_layout)
    else:
        return InputPositionAssigner(qc_layout=qc_layout)


# =============================================================================
# Legacy Position Strategy (for backward compatibility during transition)
# =============================================================================


class PositionStrategy(Protocol):
    """Protocol for user sample position strategies.

    Strategies determine how positions are assigned to user samples:
    - Generated: positions computed algorithmically by a sampler
    - Input: positions extracted from input sample data (e.g., grid_position)
    """

    def __call__(
        self,
        num_positions: int,
        input_samples: Sequence[InputSample],
    ) -> list[str]:
        """Generate or extract positions for user samples.

        Args:
            num_positions: Number of positions needed
            input_samples: Input samples (used by input-based strategies)

        Returns:
            List of position strings, length == num_positions
        """
        ...


@dataclass(frozen=True, slots=True)
class GeneratedPositionStrategy:
    """Strategy that generates positions using a sampler.

    For vial mode: positions are algorithmically generated based on
    sampler configuration (plates, rows, columns, fill order).
    """

    sampler: SamplerPositionGenerator

    def __call__(
        self,
        num_positions: int,
        input_samples: Sequence[InputSample],
    ) -> list[str]:
        """Generate positions using the sampler algorithm."""
        return self.sampler.generate_positions(num_positions)


@dataclass(frozen=True, slots=True)
class InputPositionStrategy:
    """Strategy that extracts positions from input samples.

    For plate mode: positions come from B-Fabric input (grid_position field).
    """

    def __call__(
        self,
        num_positions: int,
        input_samples: Sequence[InputSample],
    ) -> list[str]:
        """Extract positions from input samples' grid_position field."""
        if len(input_samples) < num_positions:
            raise ValueError(
                f"Not enough input samples ({len(input_samples)}) "
                f"for {num_positions} positions"
            )
        return [s.grid_position or "" for s in input_samples[:num_positions]]


def create_position_strategy(
    sampler_name: str,
    sampler_config: dict,
) -> PositionStrategy:
    """Factory function to create the appropriate position strategy.

    Args:
        sampler_name: Full sampler name like "Vanquish.vial"
        sampler_config: Merged sampler configuration dict

    Returns:
        Position strategy callable based on position_source config
    """
    position_source = sampler_config.get("position_source", "generated")

    if position_source == "generated":
        sampler = get_sampler(sampler_name, sampler_config)
        return GeneratedPositionStrategy(sampler=sampler)
    else:
        return InputPositionStrategy()
